# Generated by Django 6.0.1 on 2026-01-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('FIBRA', 'Fibra Óptica'), ('RADIO', 'Via Rádio')], max_length=10)),
                ('quantidade', models.IntegerField(default=0)),
                ('minimo', models.IntegerField(default=5, verbose_name='Estoque Mínimo')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
            },
        ),
    ]
