# Generated by Django 6.0.1 on 2026-01-28 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipamento',
            options={},
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='atualizado_em',
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='minimo',
            field=models.IntegerField(default=5, verbose_name='Alerta Mínimo'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='quantidade',
            field=models.IntegerField(default=0, verbose_name='Estoque na Empresa'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='tipo',
            field=models.CharField(choices=[('FIBRA', 'Fibra Óptica'), ('RADIO', 'Via Rádio'), ('FERRAMENTA', 'Ferramentas')], max_length=20),
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SAIDA', '🔴 Retirada (Vai para o Técnico)'), ('DEVOLUCAO', '🟢 Devolução (Volta para Empresa)'), ('BAIXA', '✅ Baixa em OS (Usado no Cliente)')], max_length=20)),
                ('quantidade', models.PositiveIntegerField()),
                ('obs', models.CharField(blank=True, max_length=100, null=True, verbose_name='OBS / Nº da OS')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('autor_movimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autor_log', to=settings.AUTH_USER_MODEL, verbose_name='Quem registrou (Secretária)')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.equipamento')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Histórico de Movimentações',
            },
        ),
        migrations.CreateModel(
            name='EstoqueTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0, verbose_name='Qtd com Técnico')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.equipamento')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meu_estoque', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carteira do Técnico',
                'verbose_name_plural': 'Carteiras dos Técnicos',
                'unique_together': {('tecnico', 'equipamento')},
            },
        ),
    ]
