# Generated by Django 6.0.1 on 2026-01-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_equipamento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='especificacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Especificações Técnicas'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='equipamentos/', verbose_name='Foto do Produto'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações Gerais'),
        ),
    ]
