# Generated by Django 6.0.1 on 2026-02-06 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_estoquetecnico_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SAIDA', '🔴 Saída (Para o Técnico)'), ('DEVOLUCAO', '🟢 Devolução (Volta para Empresa)')], default='SAIDA', max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observação do Lote')),
                ('lancado', models.BooleanField(default=False, editable=False)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável')),
            ],
            options={
                'verbose_name': '🔴 Lançamento em Lote (Vários Itens)',
                'verbose_name_plural': '🔴 Lançamentos em Lote (Vários Itens)',
            },
        ),
        migrations.CreateModel(
            name='ItemOrdem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.equipamento')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.ordemmovimentacao')),
            ],
        ),
    ]
