# Generated by Django 6.0.1 on 2026-02-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_ordemmovimentacao_itemordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemmovimentacao',
            name='tipo',
            field=models.CharField(choices=[('SAIDA', '🔴 Retirada (Sai do Estoque -> Vai pro Técnico)'), ('DEVOLUCAO', '🟢 Devolução (Sai do Técnico -> Volta pro Estoque)'), ('BAIXA', '✅ Baixa em OS (Sai do Técnico -> Cliente/Lixo)')], default='SAIDA', max_length=20),
        ),
    ]
